### PR TITLE
Python3

### PR DESCRIPTION
**Pull request by tfarago**
Roadmap
-------------

- [x] code conversion to Python3.6+ (Python 2 **will not be supported anymore**)
- [x] make tests work
- [x] make sure CI works
- [x] make sure docs are build
- [x] make flake8 happy
- [x] make examples work
- [x] clean up examples (flake8 and requirements)

### CODE REVIEW

**Comment by matze** [comment]
Hooray, now you can replace those annoying `"".format()` with [f-strings](https://www.python.org/dev/peps/pep-0498/)!

**Comment by tfarago** [comment]
Yes! And from now on I am using only that. And also, as a cherry on top, when doing this for [concert](https://github.com/ufo-kit/concert/issues/448) I can rewrite futures to asyncio! Yay, that's gonna be a looot of fun!

**Comment by matze** [comment]
> Yay, that's gonna be a looot of fun!

Not sure if irony or not :laughing:

**Comment by tfarago** [comment]
I am not so sure myself :smile:

**Pull request merged**
